imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

old_sound_rabbit_mq:
    connections:
        default:
            host:      'localhost'
            port:      5672
            user:      'guest'
            password:  'guest'
            vhost:     '/'
    producers:
        create_project:
            connection: default
            exchange_options: { name: 'create-project', type: direct }
        analyze_project:
            connection: default
            exchange_options: { name: 'analyze-project', type: direct }

    consumers:
        create_project:
            connection: default
            exchange_options: { name: 'create-project', type: direct }
            queue_options:    { name: 'create-project' }
            callback:         sonar_analyzer.create_project_service

        analyze_project:
            connection: default
            exchange_options: { name: 'analyze-project', type: direct }
            queue_options:    { name: 'analyze-project' }
            callback:         sonar_analyzer.analyze_project_service
